[package]
name = "sqlite2dir"
version = "0.1.0"
authors = ["Andreas Rottmann <a.rottmann@gmx.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.20.0"
structopt = { version = "0.3.1", default-features = false }
failure = "0.1.5"
serde_json = "1.0.40"
git2 = { version = "0.10.0", default-features = false }
